### ISSUE TITLE
Can't push bytes objects to mock-amqp-server

### ISSUE THREAD

**Issue by jpmaligne** [allan-simon/mock-amqp-server#8]
When calling :

`POST BASE_URL + '/add-message-on/' + EXCHANGE,`
 with a body which contains serialized data,

I get an error, here is the stacktrace :

```
POST  b'/add-message-on/mail_sync.sync'
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 730, in _read_ready
    self._protocol.data_received(data)
  File "/service/http_protocol.py", line 37, in data_received
    self._data_received(data)
  File "/service/http_protocol.py", line 69, in _data_received
    self._on_post(self._target, event.data)
  File "/service/http_protocol.py", line 171, in _on_post
    full_message = json.loads(data.decode('utf-8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Whe can see `json.loads` is used to handle the request' body.

I used `pickle.dumps()` to serialize my data.

Best regards !

**Comment by allan-simon** [comment]
if i remember correctly, you're supposed to post a json , that has two keys, the headers and the body of the rabbitmq message, so if for some reason your rabbitmq message handle directly a pickle.dumps() bytes , these bytes should be in the json's "body" key

**Comment by jaymoulin** [comment]
Wrong use-case. `/add-message-on/` API is supposed to handle JSON request and we're just sending data which was causing this issue.

But the problem remains in the byte array handling.

With a client like `pika`, we should be able to send byte array through AMQP but mock-amqp-server seems to handle 'utf-8' strings only which result in this error:

```
frame: <service.method.Body object at 0x7f2d1f87a588>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 730, in _read_ready
    self._protocol.data_received(data)
  File "/service/protocol.py", line 119, in data_received
    self._treat_channel_frame(frame_value)
  File "/service/protocol.py", line 364, in _treat_channel_frame
    message_data=message.content,
  File "/service/state.py", line 125, in store_message
    'body': message_data.decode('utf-8'),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
frame: <service.heartbeat.HeartBeat object at 0x7f2d1f87aa58>
```

The message I'm sending is perfectly valid through a RabbitMQ instance (I guess AMQP as-well)

We might be able to handle the `.decode` thing but it will fail for GET `/message-in-XXX` APIs due to json format

**Comment by allanlegalstart** [comment]
ok i'm wondering if the simplest way to handle this would be to have a specific endpoint that accept binary stream ?

**Comment by jaymoulin** [comment]
I don't think this will work. 
The new API would handle byte array but inner process and GET `/message-in-XXX` APIs would still fail trying to decode from utf-8 or render JSON.

Our bypass implies converting to base64 so that everything could handle it but this need the broker/test API to decode base64. I don't know how RabbitMQ manager handle that kind of messages, they may have resolved this.

**Comment by allanlegalstart** [comment]
the other possibility would be to be even more "rest" , i.e the mock HTTP entry point should rely on the `Content-Type` when you handle a message to know if he needs to handle it as a JSON with body/headers or  with the body as `octet/stream`, in which case we take the body "as it , and the ampq headers from the http headers starting with "AMQP_HEADER_*" ? 
message injected this way would be stored with an additional flag "binary" to true , and when doing GET /messages-in  you encode base64 + add the flag (as this api is talking json and is for test purpose, i think you will not avoid the base64  ),  and when giving this message through normal amqp, you can give it "as it" ?

or we can make this mock totally agnostic to the message's body, and just keep only one way to send message the body , i.e as the raw body of the http injecting request, with AMQP_HEADER ,  storing the body "as it" without trying to be smart about it,  so that you just pass it "as it" in amqp , and you base64 by default  when exposing the mock http api for test/introspection purpose
